version: "3.9"

x-workspace-source: &WORKSPACE_SOURCE
  "~/ws"
x-profile: &PROFILE
  "~/dotfiles_for_docker/profile.sh"

services:
  ws:
    container_name: alpine317-ws
    build:
      context: .
      dockerfile: Dockerfile
    ipc: host
    network_mode: "host"
    tty: true
    privileged: true
    environment:
      TERM: screen-256color
      LANG: C.UTF-8
    volumes:
      - type: bind
        source: *WORKSPACE_SOURCE
        target: /home/user/ws
      - type: bind
        source: *PROFILE
        target: /home/user/profile.sh
    working_dir: /home/user/ws
    command: /bin/bash -c "echo 'source ~/profile.sh' >> ~/.bashrc && bash"
