version: "3.9"

x-workspace-source: &WORKSPACE_SOURCE
  "~/ws"

services:
  ws:
    container_name: noetic-cuda-ws
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: noetic
    ipc: host
    network_mode: "host"
    tty: true
    privileged: true
    environment:
      TERM: screen-256color
      LANG: C.UTF-8
      DISPLAY: $DISPLAY
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: *WORKSPACE_SOURCE
        target: /home/user/ws
    working_dir: /home/user/ws
    command: /bin/bash -c "sudo apt update && sudo rosdep update && sudo rosdep install -riy --from-paths src && bash"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
